apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ol6y6hbxm-java-springboot
  janus-idp.io/tekton: ol6y6hbxm-java-springboot
  backstage.io/kubernetes-id: ol6y6hbxm-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ol6y6hbxm-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
